In [1]:
!python --version

Python 3.10.9


Basic Data Types
1. Integer
2. Float
3. String
4. Boolean

In [4]:
x = 2
type(x)

int

In [5]:
y = 2.0
type(y)

float

See Yourself: How much bits/bytes is Python int data type

In [ ]:
t, f = True, False
print(t and f)

False


In [7]:
print(t or f)

True


In [8]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [ ]:
s = "abc"
print(s * 3)

abcabcabc


### List

In [18]:
my_list = [1, 2, 4, 5,8]

In [14]:
print(my_list)

[1, 2, 4, 5]


In [15]:
type(my_list)

list

In [17]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [24]:
my_list[0:4:2]

[1, 4]

In [23]:
my_list[0::2]

[1, 4, 8]

In [25]:
my_list[0]='abc'

In [26]:
my_list

['abc', 2, 4, 5, 8]

In [27]:
my_list.pop()

8

In [29]:
my_list[-1]

5

In [30]:
my_list[:-1]

['abc', 2, 4]

In [33]:
my_list[:-1:]

['abc', 2, 4]

In [7]:
lst_2d = [[1, 2, 3], [1, 4, 9]]
print(lst_2d[0])
print(lst_2d[1][1])

[1, 2, 3]
4


In [39]:
animal = ["cat", "dog", "fish"]
for a_idx, a in enumerate(animal):
    # print(str(a_idx + 1) + " : " + a)
    print(f"{a_idx+1} : {a}")

1 : cat
2 : dog
3 : fish


In [4]:
price = 513
r = price % 10
print(f"{price//10} of 10 Rs Note \n{r} of 1 Rs Coin.")

51 of 10 Rs Note 
3 of 1 Rs Coin.


### Multiply Matrices

In [11]:
mat1 = [[1, 2], [3, 5]]
mat2 = [[1, 2], [3, 4]]
mat3 = [[0, 0], [0, 0]]
for m in range(len(mat1)):
    for n in range(len(mat2)):
        for o in range(2):
            mat3[m][n] += mat1[m][o] * mat2[o][n]

print(mat3)

[[7, 10], [18, 26]]


### List Comprehension

In [16]:
mata = [1, 2, 3, 4]
matsq = [x**2 for x in mata]
matsq

[1, 4, 9, 16]

In [17]:
matcondition = [x for x in mata if x > 2]
matcondition

[3, 4]

In [18]:
d = {"cat": "meow", "dog": "bark"}
d.items()

dict_items([('cat', 'meow'), ('dog', 'bark')])

In [19]:
d.keys()

dict_keys(['cat', 'dog'])

In [20]:
d.values()

dict_values(['meow', 'bark'])

In [22]:
d['cat']

'meow'

In [24]:
print(d.get("monkey", "N/A"))
print(d.get("cat", "N/A"))

N/A
meow


### Mutable and Immutable Concept

In [25]:
x = 2
print(id(x))

2552420040976


In [26]:
x = 3
print(id(x))

2552420041008


In [28]:
my_str = "Hello World"
print(id(my_str))

2552520679664


In [29]:
my_str = "Hello Bro"
print(id(my_str))

2552497826672


In [30]:
my_tuple = (1, 2, 3)
print(id(my_tuple))

2552521258816


In [32]:
dir(my_tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [34]:
my_tuple.__add__((5, 6))
my_tuple

(1, 2, 3)

### OOP

In [ ]:
class Student:
    def __init__(self, name, roll):
        self.name = name
        self.roll = roll

    def get_record(self):
        return self.name + " : " + self.roll


s1 = Student("Saksham", "078BCT072") # Object of Class Student
s1.get_record()

'Saksham : 078BCT072'

In [38]:
s1.name

'Saksham'

In [39]:
s1.roll

'078BCT072'

In [40]:
class Test:
    def __init__(self):
        print(self, id(self))

    def __str__(self):
        return "This is a test class with str"

    def __repr__(self):
        return "This is a test class with repr"


t1 = Test()
t2 = Test()
print(t1)
t2

This is a test class with str 2552515356240
This is a test class with str 2552515350000
This is a test class with str


This is a test class with repr

### Numpy

1. Create a numpy array
2. create a 2D array
3. find shape, size and dimension
4. use random
5. use linespace
6. create a tuple

Statistical Methods
1. min
2. max
3. sum
4. standard deviation
5. variance
6. transpose
7. dot product

In [41]:
import numpy as np

my_array = np.array([1, 2, 3])

In [42]:
my_array

array([1, 2, 3])

In [43]:
type(my_array)

numpy.ndarray

In [45]:
my_array.size

3

In [47]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_array.shape

(2, 3)

In [48]:
my_2d_array.size

6

In [56]:
random_array = np.random.randint(1, 10, (3, 3))
random_array

array([[9, 2, 9],
       [9, 6, 9],
       [4, 4, 8]])

In [57]:
np.linspace(4,9)

array([4.        , 4.10204082, 4.20408163, 4.30612245, 4.40816327,
       4.51020408, 4.6122449 , 4.71428571, 4.81632653, 4.91836735,
       5.02040816, 5.12244898, 5.2244898 , 5.32653061, 5.42857143,
       5.53061224, 5.63265306, 5.73469388, 5.83673469, 5.93877551,
       6.04081633, 6.14285714, 6.24489796, 6.34693878, 6.44897959,
       6.55102041, 6.65306122, 6.75510204, 6.85714286, 6.95918367,
       7.06122449, 7.16326531, 7.26530612, 7.36734694, 7.46938776,
       7.57142857, 7.67346939, 7.7755102 , 7.87755102, 7.97959184,
       8.08163265, 8.18367347, 8.28571429, 8.3877551 , 8.48979592,
       8.59183673, 8.69387755, 8.79591837, 8.89795918, 9.        ])

In [58]:
random_array.max()

9

In [59]:
random_array.min()

2

In [60]:
random_array.sum()

60

In [61]:
random_array.std()

2.5819888974716116

In [62]:
random_array.var()

6.666666666666668

In [63]:
random_array.transpose()

array([[9, 9, 4],
       [2, 6, 4],
       [9, 9, 8]])

In [64]:
dot_prod = np.dot(random_array, random_array)

In [65]:
dot_prod

array([[135,  66, 171],
       [171,  90, 207],
       [104,  64, 136]])

In [66]:
d = np.array([[[1,2,3]]])
print(d.ndim)
print(d.shape)
print(d.size)

3
(1, 1, 3)
3


### Matplotlib