### Numpy

In [40]:
import numpy as np
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.random.seed(42)


In [2]:
# Broadcasting
my_arr + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [3]:
my_arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
my_arr.shape

(3, 3)

In [5]:
# Matrix Multiplication
my_arr @ my_arr

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [7]:
one_mat = np.ones((3, 2), np.int32)
one_mat

array([[1, 1],
       [1, 1],
       [1, 1]])

In [11]:
# Random
rand_arr = np.random.randint(1, 10, size=(2, 4))
rand_arr

array([[3, 5, 4, 3],
       [1, 8, 2, 1]])

In [44]:
np.random.seed(42)
marks = np.random.randint(80, 100, size=(10, 4))
marks

array([[86, 99, 94, 90],
       [87, 86, 98, 90],
       [90, 83, 87, 82],
       [81, 91, 85, 81],
       [80, 91, 91, 96],
       [89, 95, 94, 94],
       [98, 91, 99, 82],
       [84, 98, 86, 88],
       [86, 97, 83, 93],
       [97, 88, 81, 99]])

In [15]:
marks.sum(axis=0)

array([894, 872, 900, 876])

In [16]:
marks.sum(axis=1)

array([363, 350, 359, 353, 338, 364, 349, 374, 342, 350])

In [17]:
marks.mean(axis=0)

array([89.4, 87.2, 90. , 87.6])

In [ ]:
marks.mean(axis=1) # Y axis ko mean values 

array([90.75, 87.5 , 89.75, 88.25, 84.5 , 91.  , 87.25, 93.5 , 85.5 ,
       87.5 ])

In [ ]:
marks.max(axis=0) # X axis ko maximum values

array([95, 95, 96, 97])

In [ ]:
marks.max() # Overall Maximum

97

In [ ]:
marks_offset = marks - marks.mean(axis=0) # WORKS ON THE BASIS OF BROADCASTING

In [38]:
marks_offset

array([[ 4.8, -2.3, -6.5,  2.8],
       [-4.2, -0.3, -3.5, -0.2],
       [ 6.8,  4.7, -4.5, -4.2],
       [-5.2,  6.7,  2.5, -3.2],
       [-0.2, -4.3,  6.5, -7.2],
       [ 9.8, -5.3, -2.5, -0.2],
       [ 0.8,  3.7,  1.5,  7.8],
       [-5.2,  0.7, -3.5,  3.8],
       [-3.2,  0.7,  1.5, -9.2],
       [-4.2, -4.3,  8.5,  9.8]])

In [36]:
marks.mean(axis=0)

array([88.2, 90.3, 86.5, 89.2])

In [50]:
marks.argmax()

1

In [ ]:
np.array([1, 2, 7, 3, 2]).argmax()

2

In [51]:
marks.argmax(axis=0)

array([6, 0, 6, 9], dtype=int64)

In [52]:
marks.argmax(axis=1)

array([1, 2, 0, 1, 3, 1, 2, 1, 1, 3], dtype=int64)

In [ ]:
help(marks.argmax) # Parameters herna lai

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None, *, keepdims=False)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [54]:
marks.T

array([[86, 87, 90, 81, 80, 89, 98, 84, 86, 97],
       [99, 86, 83, 91, 91, 95, 91, 98, 97, 88],
       [94, 98, 87, 85, 91, 94, 99, 86, 83, 81],
       [90, 90, 82, 81, 96, 94, 82, 88, 93, 99]])

In [56]:
marks.reshape(1,2,20)

array([[[86, 99, 94, 90, 87, 86, 98, 90, 90, 83, 87, 82, 81, 91, 85, 81,
         80, 91, 91, 96],
        [89, 95, 94, 94, 98, 91, 99, 82, 84, 98, 86, 88, 86, 97, 83, 93,
         97, 88, 81, 99]]])

In [ ]:
marks.reshape(1,4,10) # 3 Dimension Data

array([[[86, 99, 94, 90, 87, 86, 98, 90, 90, 83],
        [87, 82, 81, 91, 85, 81, 80, 91, 91, 96],
        [89, 95, 94, 94, 98, 91, 99, 82, 84, 98],
        [86, 88, 86, 97, 83, 93, 97, 88, 81, 99]]])

In [ ]:
marks.reshape(4,10) # 2 Dimension Data

array([[86, 99, 94, 90, 87, 86, 98, 90, 90, 83],
       [87, 82, 81, 91, 85, 81, 80, 91, 91, 96],
       [89, 95, 94, 94, 98, 91, 99, 82, 84, 98],
       [86, 88, 86, 97, 83, 93, 97, 88, 81, 99]])

### Pandas