### Numpy

In [1]:
import numpy as np
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [2]:
# Broadcasting
my_arr + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [3]:
my_arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
my_arr.shape

(3, 3)

In [5]:
# Matrix Multiplication
my_arr @ my_arr

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [7]:
one_mat = np.ones((3, 2), np.int32)
one_mat

array([[1, 1],
       [1, 1],
       [1, 1]])

In [11]:
# Random
rand_arr = np.random.randint(1, 10, size=(2, 4))
rand_arr

array([[3, 5, 4, 3],
       [1, 8, 2, 1]])

In [12]:
marks = np.random.randint(80, 100, size=(10, 4))
marks

array([[86, 91, 95, 91],
       [92, 81, 96, 81],
       [91, 89, 90, 89],
       [87, 85, 93, 88],
       [85, 91, 81, 81],
       [93, 91, 95, 85],
       [88, 88, 90, 83],
       [95, 95, 87, 97],
       [82, 80, 83, 97],
       [95, 81, 90, 84]])

In [15]:
marks.sum(axis=0)

array([894, 872, 900, 876])

In [16]:
marks.sum(axis=1)

array([363, 350, 359, 353, 338, 364, 349, 374, 342, 350])

In [17]:
marks.mean(axis=0)

array([89.4, 87.2, 90. , 87.6])

In [ ]:
marks.mean(axis=1) # Y axis ko mean values 

array([90.75, 87.5 , 89.75, 88.25, 84.5 , 91.  , 87.25, 93.5 , 85.5 ,
       87.5 ])

In [ ]:
marks.max(axis=0) # X axis ko maximum values

array([95, 95, 96, 97])

In [ ]:
marks.max() # Overall Maximum

97